export const products = [
    {
        _id: '1',
        name: 'Pure Desi Dahi',
        slug: 'pure-desi-dahi',
        description: 'Traditional handmade curd prepared from fresh A2 cow milk using authentic desi methods. Rich, creamy, and packed with natural probiotics for better digestion and immunity.',
        category: 'dahi',
        price: 80,
        images: [
            '/Photo 1.jpg',
            'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
            'https://images.pexels.com/photos/6544380/pexels-photo-6544380.jpeg',
        ],
        benefits: [
            'Made from 100% pure A2 cow milk',
            'Rich in natural probiotics',
            'Improves digestion and gut health',
            'Boosts immunity naturally',
            'No preservatives or additives',
            'Traditional clay pot fermentation',
        ],
        nutrition: {
            calories: 98,
            protein: 3.5,
            fat: 4.3,
            carbohydrates: 11.4,
            calcium: 121,
        },
        gradient: 'bg-category-teal',
        adjective: 'Shuddh'
    },
    {
        _id: '2',
        name: 'Mishti Doi',
        slug: 'mishti-doi',
        description: 'Authentic Bengali sweet curd made with caramelized sugar and fresh milk. A traditional delicacy that melts in your mouth with every spoonful.',
        category: 'mishti-doi',
        price: 120,
        images: [
            '/Photo 2.jpg',
            'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
            'https://images.pexels.com/photos/7937474/pexels-photo-7937474.jpeg',
        ],
        benefits: [
            'Traditional Bengali recipe',
            'Natural sweetness from caramelized sugar',
            'Rich and creamy texture',
            'Perfect dessert option',
            'Made in clay pots for authentic taste',
            'No artificial flavors',
        ],
        nutrition: {
            calories: 156,
            protein: 4.2,
            fat: 5.1,
            carbohydrates: 22.8,
            calcium: 135,
        },
        gradient: 'bg-category-purple',
        adjective: 'Meethi'
    },
    {
        _id: '3',
        name: 'A2 Cow Curd',
        slug: 'a2-cow-curd',
        description: 'Premium curd made exclusively from A2 beta-casein cow milk. Easier to digest and more nutritious than regular curd. Perfect for daily consumption.',
        category: 'a2-curd',
        price: 100,
        images: [
            '/Photo 3.jpg',
            'https://images.pexels.com/photos/6544380/pexels-photo-6544380.jpeg',
            'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
        ],
        benefits: [
            'Pure A2 beta-casein protein',
            'Easier to digest than A1 milk',
            'Reduces inflammation',
            'Better for lactose-sensitive individuals',
            'Higher nutritional value',
            'Supports bone health',
        ],
        nutrition: {
            calories: 102,
            protein: 4.1,
            fat: 4.5,
            carbohydrates: 10.8,
            calcium: 142,
        },
        gradient: 'bg-category-green',
        adjective: 'Paustic'
    },
    {
        _id: '4',
        name: 'Desi Lassi',
        slug: 'desi-lassi',
        description: 'Refreshing traditional lassi made from fresh dahi, lightly sweetened and flavored with a hint of cardamom.',
        category: 'lassi',
        price: 60,
        images: [
            'https://images.pexels.com/photos/7937474/pexels-photo-7937474.jpeg',
            'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
        ],
        benefits: [
            'Instant refreshing energy',
            'Rich in probiotics',
            'Traditonal thirst quencher',
            'No artificial colors',
            'Freshly churned',
        ],
        nutrition: {
            calories: 110,
            protein: 2.8,
            fat: 3.5,
            carbohydrates: 16.5,
            calcium: 110,
        },
        gradient: 'bg-brand-blue/30',
        adjective: 'Taza'
    },
];
